import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import Antd from "ant-design-vue";
import "ant-design-vue/dist/antd.less";
import "./assets/global.css";
import "./assets/color.css";
import "./assets/font.css";
createApp(App).use(store).use(router).use(Antd).mount("#app");
